SELECT COUNTY, OWNER, PROPERTY_COUNT
FROM
(
	SELECT
		'hillsborough' AS COUNTY
		,OWNER
		,COUNT(FOLIO) AS PROPERTY_COUNT

	FROM (SELECT OWNER, FOLIO FROM RAW.HILLSBOROUGH_PROP_APP_PARCEL) b
	GROUP BY OWNER

	UNION

	SELECT
		'pinellas' AS COUNTY
		,owner
		,COUNT(strap) AS PROPERTY_COUNT

	FROM (SELECT DISTINCT owner AS OWNER, strap FROM RAW.PINELLAS_PROP_APP_PARCEL) a
	GROUP BY owner
) b
ORDER BY PROPERTY_COUNT DESC;
