CREATE VIEW PRODUCTION.SHAWN_YESNER AS

SELECT DISTINCT
	pin_cs_dtls.CASE_NUMBER
	,pin_cs_dtls.DEFENDANT_NAME
	,pin_cs_dtls.DEFENDANT_ADDR AS DEFENDANT_ADDRESS
	,pin_cs_dtls.PLAINTIFF_NAME
	,CONCAT(pin_doc_flag.PATTERN, ' ~~ ', pin_cs_dtls.CASE_TYPE_EXT) AS CASE_TYPE_DESCRIPTION
  ,LEFT(pin_index.FILED_LOCATION_JUDICIAL_OFFICER, 10) AS FILING_DATE
	,pin_doc_flag.COUNTY

FROM (SELECT *, 'pinellas' AS COUNTY FROM RAW.PINELLAS_CLERK_DOC_SEARCH_FLAG) AS pin_doc_flag

LEFT JOIN RAW.PINELLAS_CLERK_CASE_DETAILS AS pin_cs_dtls
ON pin_doc_flag.CASE_NUMBER = pin_cs_dtls.CASE_NUMBER

LEFT JOIN RAW.PINELLAS_CLERK_INDEX AS pin_index
ON pin_doc_flag.CASE_NUMBER = pin_index.CASE_NUMBER

WHERE VALUE_FOUND NOT IN ('', '_')

UNION

SELECT DISTINCT
		def.CASE_NUMBER
		,def.DEFENDANT_NAME
		,def.DEFENDANT_ADDRESS
    ,pltf.PLAINTIFF_NAME
		,def.CASE_TYPE_DESCRIPTION
		,def.FILING_DATE
		,COUNTY

FROM
(
	SELECT
		CASE_NUMBER
		,CONCAT(FIRST_NAME, ' ', MIDDLE_NAME, ' ', LAST_NAME_COMPANY_NAME) AS DEFENDANT_NAME
		,PARTY_ADDRESS AS DEFENDANT_ADDRESS
		,CASE_TYPE_DESCRIPTION
		,FILING_DATE
		,'hillsborough' AS COUNTY

	FROM RAW.HILLSBOROUGH_CLERK_CIVIL
	WHERE PARTY_TYPE LIKE '%DEFENDANT%'
    AND FIRST_NAME <> ''
) def

INNER JOIN
(
	SELECT
		CASE_NUMBER
        ,CONCAT(FIRST_NAME, ' ', MIDDLE_NAME, ' ', LAST_NAME_COMPANY_NAME) AS PLAINTIFF_NAME

    FROM RAW.HILLSBOROUGH_CLERK_CIVIL
	WHERE PARTY_TYPE LIKE '%PLAINT%'
) pltf

ON def.CASE_NUMBER = pltf.CASE_NUMBER
WHERE CASE_TYPE_DESCRIPTION LIKE '%FORECLOSUR%'
AND DEFENDANT_NAME NOT LIKE '%UNKNOWN%'
;
