SELECT DISTINCT
	aba_dir.LAWYER_NAME
    ,aba_dir.FLORIDA_LAW_ELIGIBILITY
    ,aba_dir.BAR_NUMBER
    ,aba_dir.CELL_PHONE_NUMBER
    ,aba_dir.OFFICE_PHONE_NUMBER
    ,aba_dir.EMAIL
	,CONCAT(aba_dir.MAILING_ADDRESS, ' ', aba_dir.ZIP) AS ABA_MAILING_ADDRESS
    ,aba_dir.ZIP
    ,sunbiz.BIZ_NAME
    ,sunbiz.DATE_FILED
FROM RAW.SUNBIZ_ABA_ADDR_MATCH sb_aba_match

LEFT JOIN
(
	SELECT
		LAWYER_NAME
        ,FLORIDA_LAW_ELIGIBILITY
        ,REPLACE(BAR_NUMBER, '#', '') AS BAR_NUMBER
        ,REPLACE(CELL_PHONE_NUMBER, 'Cell: ', '') AS CELL_PHONE_NUMBER
        ,REPLACE(OFFICE_PHONE_NUMBER, 'Office: ', '') AS OFFICE_PHONE_NUMBER
        ,EMAIL
		,CONCAT(SUBSTRING_INDEX(REPLACE(SUBSTRING_INDEX(mailing_address, '~^~', -2), '~^~',CHAR(10)), 'FL ', 1), 'FL') AS MAILING_ADDRESS
		,SUBSTRING_INDEX(SUBSTRING_INDEX(mailing_address, 'FL ', -1), '-', 1) AS ZIP
	FROM RAW.MISC_PROF_ABA
) aba_dir

ON sb_aba_match.ABA_MAILING_ADDRESS = CONCAT(aba_dir.MAILING_ADDRESS, ' ', aba_dir.ZIP)

LEFT JOIN RAW.SUNBIZ_RECORDS sunbiz
ON sb_aba_match.SUNBIZ_MAILING_ADDRESS = sunbiz.MAILING_ADDRESS

LEFT JOIN RAW.MISC_PROF_ABA_GENERAL_DETAILS aba_gen
ON aba_dir.BAR_NUMBER = aba_gen.BAR_NUMBER;
