CREATE TABLE MISC_PROF_ABA (
  LAWYER_NAME VARCHAR(255),
  LAWYER_LINK VARCHAR(255),
  BAR_NUMBER VARCHAR(255),
  MAILING_ADDRESS VARCHAR(255),
  CELL_PHONE_NUMBER VARCHAR(255),
  OFFICE_PHONE_NUMBER VARCHAR(255),
  EMAIL VARCHAR(255),
  FLORIDA_LAW_ELIGIBILITY VARCHAR(255),
  STATE VARCHAR(255),
  TIME_STAMP VARCHAR(255)
);
COMMIT;
