CREATE TABLE PINELLAS_CLERK_CASE_DETAILS (
  CASE_NUMBER VARCHAR(255),
  DEFENDANT_NAME VARCHAR(255),
  DEFENDANT_ADDR VARCHAR(255),
  PLAINTIFF_NAME VARCHAR(255),
  CASE_TYPE_EXT VARCHAR(255),
  UNIFORM_CASE_NUM VARCHAR(255)
);
COMMIT;
