CREATE TABLE PINELLAS_CLERK_INDEX (
  CASE_NUMBER VARCHAR(255),
  CITATION_NUMBER VARCHAR(255),
  STYLE_DEFENDANT_INFO VARCHAR(255),
  FILED_LOCATION_JUDICIAL_OFFICER VARCHAR(255),
  TYPE VARCHAR(255),
  CHARGES VARCHAR(255),
  CASE_URL VARCHAR(355)
);
COMMIT;
