CREATE TABLE SUNBIZ_RECORDS (
  BIZ_NAME VARCHAR(600),
  DOC_NUM VARCHAR(600),
  FEI_EIN VARCHAR(600),
  DATE_FILED VARCHAR(600),
  EFFECTIVE_DATE VARCHAR(600),
  STATE VARCHAR(600),
  STATUS VARCHAR(600),
  PRINCIPAL_ADDRESS VARCHAR(600),
  MAILING_ADDRESS VARCHAR(600),
  REGISTERED_AGENT VARCHAR(600),
  REGISTERED_AGENT_ADDRESS VARCHAR(1500),
  AUTHORIZED_PERSON VARCHAR(1500),
  ANNUAL_REPORT VARCHAR(600)
);
COMMIT;
