CREATE TABLE HILLSBOROUGH_CLERK_PROBATE (
	CASE_CATEGORY VARCHAR(255),
	CASE_TYPE_DESCRIPTION VARCHAR(255),
	CASE_NUMBER VARCHAR(255),
	TITLE VARCHAR(255),
	FILING_DATE VARCHAR(255),
	PARTY_TYPE VARCHAR(255),
	FIRST_NAME VARCHAR(255),
	MIDDLE_NAME VARCHAR(255),
	LAST_NAME_COMPANY_NAME VARCHAR(255),
	DATE_OF_DEATH VARCHAR(255),
	PARTY_ADDRESS VARCHAR(255),
	ATTORNEY VARCHAR(255)
);
COMMIT;
