CREATE TABLE PINELLAS_PERMITS (
  DATE VARCHAR(999),
  RECORD_TYPE VARCHAR(999),
  record_number VARCHAR(999),
  STATUS VARCHAR(999),
  ACTION VARCHAR(999),
  ADDRESS VARCHAR(999),
  PROJECT_NAME VARCHAR(999),
  EXPIRATION_DATE VARCHAR(999),
  DESCRIPTION VARCHAR(999)
);
COMMIT;
